name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # This ensures all history and tags are fetched
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN for checkou
      - name: define git identity
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2
        with:
          version: 9.5.0
      - run: pnpm install

      - run: pnpm run build
      - name: npm version patch
        run: npm version patch

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Push version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git push --follow-tags
